### ISSUE TITLE
How to add other users?

### ISSUE THREAD

**Issue by Ronaldvr** [ellite/Wallos#13]
Adding household members implies they could also be users this does not seem to be the case?
It would in a sense also open the door for gift subscriptions, i.e. subscriptions for 1 person paid for by another

**Comment by nebbishOne** [comment]
I just submitted issue #14 with the same basic question. I've looked into the code and the "households" table just has a Name field right now, so yeah, it seems those names can't login. I think the only time you can create a new user is when there are no other users defined yet and so just 1 login possible. Correct me if I'm wrong, of course, @ellite .

**Comment by ellite** [comment]
Hi.
For the moment only on account can login.
The idea with the household is that everyone can login with the same account and add the subscriptions for their household using the household member.
Implementing multi login will require a total redesign of the database, so, it will not be done for now, until I fix all the issues. Sorry.

**Comment by Ronaldvr** [comment]
This weekend I thought of an 'interim' solution: Just create an extra field, "Beneficiary" with the same choices as Paid by . Then you do not need additional logins but can distinguish between who pays for a subscription, and for whom it actually is, so I can log my gift subscription for a game pass for instance

**Comment by carsaig** [comment]
huh, I was a little disappointed to see it only supports one user :-( I'm aware of the implications adding multi-user. Still - that makes perfect sense as people have their own subscriptions nowadays. Throwing everything into one pot is not useful. Even in a two-person household. However - good work. Keep going!

**Comment by ellite** [comment]
It's being worked on.
But it's taking a s*** load of time.

It's not an easy migration because of the dynamic currencies, categories and paying methods.

There's a new admin page and every new string has to be translated in 17 languages.

Progress:
- Admin page is almost ready
- DB Migration script is done
- 100% of the queries on the Ajax endpoints have been changed to use the new DB schema
- I estimate around 90% of the queries using on Dashboard, Statistics and Settings page have been changed to use the new DB schema
- All the new strings have been translated 

Missing:
- Remaining 10% of queries
- All the endpoints for the Admin page (whether registrations are open, user management, email settings for password reset)
- Cronjobs should run for all users
- User registration
- Password reset
- Something else I'm probably forgetting
- Lots of testing

But yeah, might take a while.

Regards.

**Comment by carsaig** [comment]
Aye....good man! Keep it up :-) Take your time.

**Comment by ellite** [comment]
This is the new Admin page:
![adminpage](https://github.com/ellite/Wallos/assets/3831180/07ff7b1f-cdb9-427c-a12f-728553ccd812)

**Comment by ellite** [comment]
Version 2.0 with user account creation is now live.

**Comment by Nec83** [comment]
@ellite Great work and thank you for this feature addition!

Just to check, what is the intention with having multiple users being able to register? From the looks of things, they get their own logins and can add subscriptions but can't see or view any subscriptions assigned to them for notification so this is a pretty blind way for them to try and manage subscriptions assigned to them?

Any way to potentially expand on this feature to make them view the subscriptions when they're added to the same Household or at the very least the ones assigned to them for notifications?

Thank you for your efforts and making this great app!
