### ISSUE TITLE
Bug: Cannot change currency

### ISSUE THREAD

**Issue by vinkmr** [ellite/Wallos#445]
Wallos version : v2.17.0
Installation type : docker-compose

![image](https://github.com/user-attachments/assets/c1924738-2ca0-4b67-9436-b1885be3f9f1)

The chosen currency type does seem to stick, it defaults to the chosen default currency.
Please let me know if I can provide more logs.

**Comment by ellite** [comment]
Hi. Can you show me the currencies part of the settings page, please?

**Comment by vinkmr** [comment]
Sure. Here its is:

![image](https://github.com/user-attachments/assets/a8f2f117-1cb4-4007-8156-1e27ccce0f93)

BTW, it works now. I provided an API key for fixer, and now the currency is shown correctly. I thought the API key was optional, if I didn't need currency conversion.

**Comment by ellite** [comment]
Since there's no date after "Exchange rates last update on" I believe the issue is:
- On the `User Details` section of the settings you have `Euro `as the main currency.
- On the `Display Settings` section of the settings you have `Calculate and show monthly price for all subscriptions` selected.

Since the currency conversion cannot be performed it will convert 1 to 1.

**Comment by vinkmr** [comment]
Geil! That makes sense. Thanks for the great work!
