### ISSUE TITLE
Feature tweak - on Statistics page

### ISSUE THREAD

**Issue by kazzyUK** [ellite/Wallos#643]
When on the Statistics view.. and then Filter by Category it gives some stats about that cat.. there is a pie chart split view.

So for example i filter by Entertainment Services.

It shows  Active Subscriptions  = 3 and a pie chart showing Payment methods... and that's it.. it would be nice to see what the subscriptions are. 

I had another that shows 2 Active Cloud Services.. one paid by Direct Debit, another by PayPal.. but looking at that screen i couldnt remember what was being paid by PayPal.. without going back to the main screen list.

Hover over the sections to the pie chart just says Direct Debit (2). etc...   that not really helpful

Hope that made sense. Thanks.

**Comment by ellite** [comment]
Hi.
This is by design. The statistics page is about numbers, not subscriptions. Only the most expensive is there.
I have built the same filters + sorting on the dashboard, so this info can easily be found there.
For now there's no plans to change it.
Sorry.

Thank you for the suggestions.

Best regards.
